[build]
builder = "NIXPACKS"
buildCommand = "cd server && npm install && cd ../client && npm install && npm run build"
sourceDir = "server"

[deploy]
startCommand = "node index.js"

[environment]
NODE_ENV = "production"
