import React from 'react';

const Icon = (props) => React.createElement('span', props);

export default Icon;

export const Accessible = Icon;
export const AccountCircle = Icon;
export const Add = Icon;
export const AdminPanelSettings = Icon;
export const Analytics = Icon;
export const ArrowBack = Icon;
export const Article = Icon;
export const Assessment = Icon;
export const Assignment = Icon;
export const Backup = Icon;
export const BugReport = Icon;
export const Business = Icon;
export const Campaign = Icon;
export const Cancel = Icon;
export const Check = Icon;
export const CheckCircle = Icon;
export const Circle = Icon;
export const Close = Icon;
export const CloudDownload = Icon;
export const CloudUpload = Icon;
export const ContentCopy = Icon;
export const Delete = Icon;
export const Description = Icon;
export const Download = Icon;
export const Edit = Icon;
export const Elderly = Icon;
export const Email = Icon;
export const Error = Icon;
export const Event = Icon;
export const ExpandLess = Icon;
export const ExpandMore = Icon;
export const FamilyRestroom = Icon;
export const FilterList = Icon;
export const Gavel = Icon;
export const Group = Icon;
export const Help = Icon;
export const Home = Icon;
export const Info = Icon;
export const Language = Icon;
export const Lock = Icon;
export const LockOutlined = Icon;
export const Logout = Icon;
export const Notifications = Icon;
export const Palette = Icon;
export const Pending = Icon;
export const People = Icon;
export const Person = Icon;
export const PersonAdd = Icon;
export const Phone = Icon;
export const PlayArrow = Icon;
export const Print = Icon;
export const QrCode = Icon;
export const QrCodeScanner = Icon;
export const Refresh = Icon;
export const Save = Icon;
export const Schedule = Icon;
export const Search = Icon;
export const Security = Icon;
export const Send = Icon;
export const Settings = Icon;
export const Shield = Icon;
export const SmartToy = Icon;
export const Sms = Icon;
export const TrendingUp = Icon;
export const Upload = Icon;
export const VerifiedUser = Icon;
export const Visibility = Icon;
export const Warning = Icon;

